# helm-chart/values.yaml
replicaCount: 2

image:
  repository: kirubarp/jenkinsrepo      # Update this to your Docker repository
  tag: "18"                             # Update this to the correct tag of your image
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: react-app.local
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 300m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
